services:
  postgres:
    image: postgres:16-alpine
    container_name: multi-saas-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresql"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multi-saas-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgresql:postgresql@postgres:5432/postgresql
      NEXTAUTH_SECRET: jV0sMKY0MQP7Vzkf9p1Gi04Ueb3LCwaHC2L0zq1ofFk=
      NEXTAUTH_URL: http://localhost:3000
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
