services:
  postgres:
    image: postgres:16-alpine
    container_name: multi-saas-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresql"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multi-saas-app
    restart: unless-stopped
    ports:
      - "3035:3000"
    environment:
      DATABASE_URL: "postgresql://postgresql:postgresql@postgres:5432/postgresql"
      NEXTAUTH_SECRET: "jV0sMKY0MQP7Vzkf9p1Gi04Ueb3LCwaHC2L0zq1ofFk="
      NEXTAUTH_URL: "https://saas.erdoganyesil.org"
      NODE_ENV: "production"
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
      NEXT_TELEMETRY_DISABLED: "1"
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
